import { DATA } from "@/data/resume";

/**
 * Every piece of page metadata, in one place.
 *
 * Next.js collected this through its `Metadata` export and expanded it into
 * tags at build time. Astro has no such indirection — the layout writes the
 * tags itself — so the values live here, shared by the layout, the 404 page,
 * the web manifest, `robots.txt` and the sitemap.
 */
export const SITE_URL = DATA.url;

export const JOB_TITLE = "Fullstack Team Lead & AI Engineer";

export const TITLE = `${DATA.name} — ${JOB_TITLE}`;

export const DESCRIPTION =
  "Fullstack Team Lead & AI Engineer with 4+ years of experience. Building scalable solutions with modern stacks, AI integration, and DevOps practices. Based in Havana, Cuba.";

/** 1.91:1, generated by `scripts/generate-og-image.mjs`. */
export const OG_IMAGE = {
  url: `${SITE_URL}/og.png`,
  width: 1200,
  height: 630,
  alt: `${DATA.name} — ${JOB_TITLE} Portfolio`,
  type: "image/png",
} as const;

export const KEYWORDS = [
  DATA.name,
  "EduardoProfe666",
  "Eduardo González Martell",
  "Fullstack Developer",
  "Full Stack Engineer",
  "AI Engineer",
  "Artificial Intelligence",
  "Team Lead",
  "Tech Lead",
  "DevOps Engineer",
  "Cloud Infrastructure",
  "React",
  "Next.js",
  "Astro",
  "TypeScript",
  "Python",
  ".NET",
  "Node.js",
  "React Native",
  "Expo",
  "Software Engineer",
  "Web Developer",
  "Mobile Developer",
  "Portfolio",
  "Cuba",
  "Havana",
  "CUJAE",
  "n8n",
  "AWS",
  "Railway",
  "DigitalOcean",
] as const;

export const AUTHORS = [
  { name: DATA.name, url: SITE_URL },
  { name: "EduardoProfe666", url: "https://github.com/EduardoProfe666" },
] as const;

export const SOCIAL_HANDLE = "@EduardoProfe666";

export const APPLICATION_NAME = "Eduardo González Portfolio";

/** Matches the resolved `--background` in either theme. */
export const THEME_COLOR = { light: "#ffffff", dark: "#08090a" } as const;
