import { BackToTop } from "@/components/main/back-to-top";
import { FeedbackListener } from "@/components/main/feedback-listener";
import { MotionProvider } from "@/components/main/motion-provider";
import { HtmlLang } from "@/components/main/html-lang";
import { ThemeColor } from "@/components/main/theme-color";
import { Spotlight } from "@/components/main/spotlight";
import { JsonLd } from "@/components/common/json-ld";
import { I18nProvider } from "@/i18n/provider";
import Navbar from "@/components/main/navbar";
import { ThemeProvider } from "@/components/main/theme-provider";
import { TooltipProvider } from "@/components/common/tooltip";
import { DATA } from "@/data/resume";
import { cn } from "@/lib/utils";
import type { Metadata, Viewport } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});

const TITLE = `${DATA.name} — Fullstack Team Lead & AI Engineer`;
const DESCRIPTION =
  "Fullstack Team Lead & AI Engineer with 4+ years of experience. Building scalable solutions with modern stacks, AI integration, and DevOps practices. Based in Havana, Cuba.";

/** 1.91:1, generated by `scripts/generate-og-image.mjs`. */
const OG_IMAGE = {
  url: "/og.png",
  width: 1200,
  height: 630,
  alt: `${DATA.name} — Fullstack Team Lead & AI Engineer Portfolio`,
  type: "image/png",
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    // #08090a is `--background` in the dark theme; anything close but not
    // equal shows as a seam between the page and the browser chrome.
    { media: "(prefers-color-scheme: dark)", color: "#08090a" },
  ],
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  colorScheme: "light dark",
};

export const metadata: Metadata = {
  metadataBase: new URL(DATA.url),
  title: {
    default: TITLE,
    template: `%s | ${DATA.name}`,
  },
  description: DESCRIPTION,
  applicationName: "Eduardo González Portfolio",
  generator: "Next.js",
  creator: DATA.name,
  publisher: DATA.name,
  category: "technology",
  classification: "Portfolio",
  referrer: "origin-when-cross-origin",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  openGraph: {
    title: TITLE,
    description: DESCRIPTION,
    url: DATA.url,
    images: [OG_IMAGE],
    siteName: DATA.name,
    locale: "en_US",
    alternateLocale: ["es_ES", "fr_FR", "de_DE", "it_IT"],
    type: "profile",
    firstName: "Eduardo",
    lastName: "González",
    username: "EduardoProfe666",
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  twitter: {
    title: TITLE,
    description: DESCRIPTION,
    card: "summary_large_image",
    images: [OG_IMAGE],
    site: "@EduardoProfe666",
    creator: "@EduardoProfe666",
  },
  keywords: [
    DATA.name,
    "EduardoProfe666",
    "Eduardo González Martell",
    "Fullstack Developer",
    "Full Stack Engineer",
    "AI Engineer",
    "Artificial Intelligence",
    "Team Lead",
    "Tech Lead",
    "DevOps Engineer",
    "Cloud Infrastructure",
    "React",
    "Next.js",
    "TypeScript",
    "Python",
    ".NET",
    "Node.js",
    "React Native",
    "Expo",
    "Software Engineer",
    "Web Developer",
    "Mobile Developer",
    "Portfolio",
    "Cuba",
    "Havana",
    "CUJAE",
    "n8n",
    "AWS",
    "Railway",
    "DigitalOcean",
  ],
  authors: [
    { name: DATA.name, url: DATA.url },
    { name: "EduardoProfe666", url: "https://github.com/EduardoProfe666" },
  ],
  // No `languages` map: every translation lives at this one URL, and an
  // `hreflang` cluster whose entries all resolve to the same page is either
  // ignored or reported as an error in Search Console.
  alternates: {
    canonical: DATA.url,
  },
  manifest: "/manifest.webmanifest",
  icons: {
    // `app/favicon.ico` is picked up automatically and now carries 16/32/48/256,
    // the sizes Google Search and the browser chrome actually read. These add
    // the PNG variants that installs and iOS home screens need.
    icon: [
      { url: "/icon-192.png", type: "image/png", sizes: "192x192" },
      { url: "/icon-512.png", type: "image/png", sizes: "512x512" },
    ],
    apple: [{ url: "/apple-icon.png", sizes: "180x180" }],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Only hosts the page actually talks to at runtime: the icon cloud
            pulls brand glyphs from Simple Icons, the project cards read star
            counts from the GitHub API. Fonts are self-hosted by next/font. */}
        <link rel="preconnect" href="https://cdn.simpleicons.org" />
        <link rel="dns-prefetch" href="https://cdn.simpleicons.org" />
        <link rel="preconnect" href="https://api.github.com" />
        {/* The hero portrait is the Largest Contentful Paint element, and it
            lives behind two client components. Preloading makes the request
            discoverable while the HTML is still parsing. */}
        <link
          rel="preload"
          as="image"
          href={DATA.avatarUrl}
          type="image/avif"
          fetchPriority="high"
        />
        <meta name="author" content={DATA.name} />
        <meta name="geo.region" content="CU-03" />
        <meta name="geo.placename" content="Havana" />
        <meta name="geo.position" content="23.1136;-82.3666" />
        <meta name="ICBM" content="23.1136, -82.3666" />
        <JsonLd />
      </head>
      <body
        suppressHydrationWarning
        className={cn(
          "min-h-screen bg-background font-sans antialiased max-w-2xl mx-auto py-12 sm:py-24 px-6",
          fontSans.variable
        )}
      >
        {/* Reading progress. The keyframes are tied to the document's own
            scroll timeline in CSS, so there is no listener, no rAF loop and
            nothing to recompute on resize; browsers without `animation-timeline`
            never show it at all. */}
        <div
          aria-hidden="true"
          className="scroll-progress pointer-events-none fixed inset-x-0 top-0 z-50 h-[2px] bg-foreground/50"
        />
        <a href="#hero" className="sr-only focus:not-sr-only focus:absolute focus:top-4 focus:left-4 focus:z-50 focus:px-4 focus:py-2 focus:bg-foreground focus:text-background focus:rounded-md focus:text-sm focus:font-medium">
          Skip to content
        </a>
        <ThemeProvider attribute="class" defaultTheme="light">
          <I18nProvider>
            <HtmlLang />
            <ThemeColor />
            <FeedbackListener />
            <MotionProvider>
              <TooltipProvider delayDuration={100}>
                {children}
                <Navbar />
                <Spotlight />
                <BackToTop />
              </TooltipProvider>
            </MotionProvider>
          </I18nProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
